name: docker-base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - libcurl
  - curl
  - pip:
    - pandas
    - numpy
    - dash
    - mysql-connector-python
    - PyVCF3==1.0.3
    - pymysql
    - flask-caching
    - dash-auth
    - dash-extensions
    - requests
